In [68]:
import numpy as np
import pandas as pd

In [144]:
buy_2018 = pd.read_csv('C://pythonworks/miniminiproject/data/buy_2018.csv',  encoding='euc-kr')
buy_2018 = buy_2018.iloc[:,1:]
buy_2018['date'] = pd.to_datetime(buy_2018['date'])
buy_2018['age'] = buy_2018['age'].astype('str')
weight = pd.read_csv('C://pythonworks/miniminiproject/data/weight_2018 - 세종제외.csv')
weather = pd.read_csv('C://pythonworks/miniminiproject/data/region_weather.csv',  encoding='euc-kr')

In [94]:
(buy_2018.sex=='M')&(buy_2018.age=='20')

0         False
1         False
2         False
3         False
4          True
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...  
600582    False
600583    False
600584    False
600585    False
600586    False
600587     True
600588    False
600589    False
600590    False
600591    False
600592    False
600593    False
600594    False
600595    False
600596    False
600597     True
600598    False
600599    False
600600    False
600601    False
600602    False
600603    False
600604    False
600605    False
600606    False
600607     True
600608    False
600609    False
600610    False
600611    False
Length: 600612, dtype: b

In [147]:
weight.loc[weight.age==20].sort_values('행정구역별(읍면동)')

Unnamed: 0 행정구역별(읍면동)   총인구(명)  총인구_남자(명)  총인구_여자(명)  age  man_weight  \
0            0        강원도   192236     110222      82014   20    0.029502   
15          16        경기도  1767281     949263     818018   20    0.254077   
12          13       경상남도   393322     224549     168773   20    0.060102   
9           10       경상북도   319936     183327     136609   20    0.049069   
11          12      광주광역시   218905     114641     104264   20    0.030684   
5            6      대구광역시   331747     180334     151413   20    0.048268   
3            3      대전광역시   236256     126722     109534   20    0.033918   
1            1      부산광역시   458036     241822     216214   20    0.064725   
7            8      서울특별시  1490977     725833     765144   20    0.194274   
2            2      울산광역시   150027      86189      63838   20    0.023069   
4            5      인천광역시   402803     212428     190375   20    0.056858   
6            7       전라남도   189330     107911      81419   20    0.028883   
8            9       전라북도   228970     125921     103049   20    0.033704   
10          11    제주특별자치도    81493      44368      37125   20    0.011875   
13          14       충청남도   322483     178072     144411   20    0.047662   
14          15       충청북도   221164     124523      96641   20    0.033329   

    woman_weight  Unnamed: 8  Unnamed: 9  
0       0.025090     3736125     3268841  
15      0.250247     3736125     3268841  
12      0.051631     3736125     3268841  
9       0.041791     3736125     3268841  
11      0.031896     3736125     3268841  
5       0.046320     3736125     3268841  
3       0.033509     3736125     3268841  
1       0.066144     3736125     3268841  
7       0.234072     3736125     3268841  
2       0.019529     3736125     3268841  
4       0.058239     3736125     3268841  
6       0.024908     3736125     3268841  
8       0.031525     3736125     3268841  
10      0.011357     3736125     3268841  
13      0.044178     3736125     3268841  
14      0.029564     3736125     3268841

In [149]:
weight_temp = weight.loc[weight.age==20].sort_values('행정구역별(읍면동)')[['행정구역별(읍면동)','man_weight']]

In [153]:
weight_temp['man_weight'].sum()

1.00000000001

In [156]:
np.array(weight_temp)

array([['강원도', 0.02950168958],
       ['경기도', 0.2540768845],
       ['경상남도', 0.06010211114],
       ['경상북도', 0.04906875438999999],
       ['광주광역시', 0.030684465860000003],
       ['대구광역시', 0.048267657],
       ['대전광역시', 0.03391803004],
       ['부산광역시', 0.06472535046],
       ['서울특별시', 0.19427428149999998],
       ['울산광역시', 0.023069088959999998],
       ['인천광역시', 0.05685784068],
       ['전라남도', 0.028883134260000005],
       ['전라북도', 0.03370363679],
       ['제주특별자치도', 0.01187540567],
       ['충청남도', 0.047662216869999996],
       ['충청북도', 0.03332945231]], dtype=object)

In [157]:
weight_temp.T

0         15         12         9          11         5   \
행정구역별(읍면동)        강원도       경기도       경상남도       경상북도      광주광역시      대구광역시   
man_weight  0.0295017  0.254077  0.0601021  0.0490688  0.0306845  0.0482677   

                  3          1         7          2          4          6   \
행정구역별(읍면동)     대전광역시      부산광역시     서울특별시      울산광역시      인천광역시       전라남도   
man_weight  0.033918  0.0647254  0.194274  0.0230691  0.0568578  0.0288831   

                   8          10         13         14  
행정구역별(읍면동)       전라북도    제주특별자치도       충청남도       충청북도  
man_weight  0.0337036  0.0118754  0.0476622  0.0333295

In [146]:
weight.sum()

Unnamed: 0                                                   3369
행정구역별(읍면동)      강원도부산광역시울산광역시대전광역시인천광역시대구광역시전라남도서울특별시전라북도경상북도제...
총인구(명)                                                   37230744
총인구_남자(명)                                                19016407
총인구_여자(명)                                                18214337
age                                                          3200
man_weight                                                      5
woman_weight                                                    5
Unnamed: 8                                              304262512
Unnamed: 9                                              291429392
dtype: object

In [102]:
(buy_2018.date=='2018-01-01')

0          True
1          True
2          True
3          True
4          True
5          True
6          True
7          True
8          True
9          True
10         True
11         True
12         True
13         True
14         True
15         True
16         True
17         True
18         True
19         True
20         True
21         True
22         True
23         True
24         True
25         True
26         True
27         True
28         True
29         True
          ...  
600582    False
600583    False
600584    False
600585    False
600586    False
600587    False
600588    False
600589    False
600590    False
600591    False
600592    False
600593    False
600594    False
600595    False
600596    False
600597    False
600598    False
600599    False
600600    False
600601    False
600602    False
600603    False
600604    False
600605    False
600606    False
600607    False
600608    False
600609    False
600610    False
600611    False
Name: date, Length: 6006

In [104]:
(weather.일시 =='2018-01-01')

0         True
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
11865    False
11866    False
11867    False
11868    False
11869    False
11870    False
11871    False
11872    False
11873    False
11874    False
11875    False
11876    False
11877    False
11878    False
11879    False
11880    False
11881    False
11882    False
11883    False
11884    False
11885    False
11886    False
11887    False
11888    False
11889    False
11890    False
11891    False
11892    False
11893    False
11894    False
Name: 일시, Length: 11895, dtype: bool

In [113]:
weather.loc[weather.일시 =='2018-01-01'].sort_values('지점명')

지점명          일시  평균기온  최저기온  최고기온  강수계속시간  일강수량  최대풍속  평균풍속  \
0          강원도  2018-01-01  -4.5 -10.5   3.4     NaN   NaN   3.6   1.0   
2190       경기도  2018-01-01  -1.7  -6.9   4.7     NaN   NaN   3.4   1.0   
7300      경상남도  2018-01-01   1.8  -1.9   5.5     NaN   NaN   5.3   1.8   
4380      경상북도  2018-01-01   2.0  -1.1   6.2     NaN   NaN   5.5   2.7   
8030     광주광역시  2018-01-01   2.3  -1.0   7.1     NaN   NaN   3.7   1.6   
5110     대구광역시  2018-01-01   1.3  -1.3   5.0     NaN   NaN   7.7   3.1   
3650     대전광역시  2018-01-01  -0.7  -5.3   4.9     NaN   NaN   2.7   1.0   
8760     부산광역시  2018-01-01   2.7  -1.1   7.4     NaN   NaN   7.6   2.7   
730      서울특별시  2018-01-01  -1.3  -5.1   3.8     NaN   NaN   3.8   1.4   
6570     울산광역시  2018-01-01   2.1  -0.4   6.2     NaN   NaN   7.1   3.3   
1460     인천광역시  2018-01-01  -0.3  -2.7   2.7     NaN   NaN   2.9   1.6   
9490      전라남도  2018-01-01   3.3  -0.2   7.2     NaN   NaN   9.2   4.5   
5840      전라북도  2018-01-01   1.0  -2.7   5.2     NaN   NaN   4.3   1.2   
10220  제주특별자치도  2018-01-01   6.4   4.0   8.8     NaN   NaN   7.2   3.5   
10950     충청남도  2018-01-01  -2.8  -8.5   3.8     NaN   NaN   3.4   0.9   
2920      충청북도  2018-01-01  -0.2  -4.3   4.7     NaN   NaN   3.1   1.1   

       최소상대습도  ...  가조시간  합계일조시간  합계일사량  일최심신적설  일최심적설  평균중하층운량  평균지면온도  \
0        20.0  ...   9.6     8.0  10.90     NaN    NaN      NaN    -2.8   
2190     25.0  ...   9.7     8.3   7.56     NaN    NaN      0.9    -1.2   
7300     18.0  ...   9.8     8.7  12.32     NaN    NaN      0.0     1.9   
4380     20.0  ...   9.8     8.9   6.65     NaN    NaN      0.0     1.1   
8030     33.0  ...   9.8     8.9  12.02     NaN    NaN      0.4     1.3   
5110     18.0  ...   9.8     9.0  10.87     NaN    NaN      0.0     0.9   
3650     26.0  ...   9.7     8.0   6.41     NaN    NaN      0.5    -0.2   
8760     19.0  ...   9.9     9.3  11.66     NaN    NaN      0.0     1.5   
730      19.0  ...   9.6     8.3   6.14     NaN    NaN      0.9    -1.7   
6570     17.0  ...   9.8     9.1    NaN     NaN    NaN      0.0     0.7   
1460     22.0  ...   9.6     8.7   4.82     NaN    NaN      0.3    -1.1   
9490     31.0  ...   9.9     8.6   8.25     NaN    NaN      0.0     3.8   
5840     32.0  ...   9.8     8.2  10.96     NaN    NaN      0.6     1.5   
10220    41.0  ...  10.0     2.7   5.97     NaN    NaN      5.3     5.6   
10950    26.0  ...   9.7     8.0    NaN     NaN    NaN      NaN    -1.1   
2920     29.0  ...   9.7     8.6   9.12     NaN    NaN      0.3    -1.0   

       합계대형증발량  합계소형증발량  안개계속시간  
0          1.2      1.7     NaN  
2190       0.9      1.3     NaN  
7300       1.8      2.6     NaN  
4380       1.7      2.4     NaN  
8030       1.5      2.1     NaN  
5110       1.9      2.7     NaN  
3650       0.8      1.2     NaN  
8760       2.4      3.4     NaN  
730        1.1      1.6     NaN  
6570       NaN      NaN     NaN  
1460       1.0      1.4     NaN  
9490       2.1      3.1     NaN  
5840       1.3      1.9     NaN  
10220      1.4      2.0     NaN  
10950      NaN      NaN     NaN  
2920       1.1      1.6     NaN  

[16 rows x 22 columns]

In [118]:
weather_temp = weather.loc[weather.일시 =='2018-01-01'].sort_values('지점명')['평균기온']

In [122]:
np.dot(weight_temp.T,weather_temp)

0.06850624642709996

In [ ]:
(buy_2018.date=='2018-01-01')&(wheather.일시 =='2018-01-01'),wheather.loc[wheather.일시 =='2018-01-01']['평균기온']

In [257]:
def find_weight(buy_2018_sex,buy_2018_age):
    if buy_2018_sex=='M':
        weight_temp = weight.loc[weight.age==buy_2018_age].sort_values('행정구역별(읍면동)')['man_weight']
    else :
        weight_temp = weight.loc[weight.age==buy_2018_age].sort_values('행정구역별(읍면동)')['woman_weight']
    return np.array(weight_temp).reshape(16,1)
    

In [233]:
buy_2018_date = buy_2018[['date']]

In [234]:
buy_2018_date.size

600612

In [239]:
def find_weather(buy_2018_date):
    weather_temp = weather.loc[weather.일시 ==buy_2018_date].sort_values('지점명')['평균기온']
    return np.array(weather_temp)

In [182]:
find_weight('M',20).T.shape

(1, 16)

In [263]:
find_weight('F',20)

array([[0.02508963],
       [0.25024711],
       [0.05163084],
       [0.04179126],
       [0.03189632],
       [0.04632009],
       [0.03350851],
       [0.06614393],
       [0.23407195],
       [0.01952925],
       [0.0582393 ],
       [0.0249076 ],
       [0.03152463],
       [0.01135724],
       [0.04417804],
       [0.0295643 ]])

In [240]:
find_weather('2018-01-01')

array([-4.5, -1.7,  1.8,  2. ,  2.3,  1.3, -0.7,  2.7, -1.3,  2.1, -0.3,
        3.3,  1. ,  6.4, -2.8, -0.2])

In [253]:
buy_2018['date']= buy_2018['date'].astype('str')

In [254]:
buy_2018['date'][0]

'2018-01-01'

In [246]:
find_weather('2018-01-01')

array([-4.5, -1.7,  1.8,  2. ,  2.3,  1.3, -0.7,  2.7, -1.3,  2.1, -0.3,
        3.3,  1. ,  6.4, -2.8, -0.2])

In [261]:
buy_2018['sex'][0]

'F'

In [268]:
buy_2018['age'] = buy_2018[['age']].astype('int64')

In [269]:
buy_2018['age'][0]

20

In [277]:
a = find_weight(buy_2018['sex'][0],buy_2018['age'][0])

In [278]:
b = find_weather(buy_2018['date'][0])

In [280]:
np.dot(find_weight(buy_2018['sex'][0],buy_2018['age'][0]).T,find_weather(buy_2018['date'][0]))

array([-0.29705431])

In [281]:
buy_2018['mean_temp'] = 0

In [292]:
buy_2018.iloc[0,5] = np.dot(find_weight(buy_2018['sex'][0],buy_2018['age'][0]).T,find_weather(buy_2018['date'][0]))

In [294]:
buy_2018.age.size

600612

In [ ]:
#16,n 이면, 결과값을 그냥 array로 나올테니,
#60만,n
#을 데이터 프레임으로, 콩켓.

In [296]:
for i in np.arange(buy_2018.age.size):
    buy_2018.iloc[i,5] = np.dot(find_weight(buy_2018['sex'][i],buy_2018['age'][i]).T,find_weather(buy_2018['date'][i]))

In [298]:
buy_2018.to_csv('C://pythonworks/miniminiproject/data/buy_2018_mean_temp.csv',  encoding='euc-kr')

In [279]:
np.dot(a.T,b)

array([-0.29705431])

In [197]:
buy_2018.head()

date sex age sm_pr  quant
0 2018-01-01   F  20   가공란     37
1 2018-01-01   F  30   가공란     16
2 2018-01-01   F  40   가공란      9
3 2018-01-01   F  50   가공란      3
4 2018-01-01   M  20   가공란     13

In [230]:
find_weight(buy_2018[['sex']],buy_2018[['age']])

ValueError: Cannot index with multidimensional key

TypeError: find_weight() missing 1 required positional argument: 'buy_2018_age'

In [200]:
np.dot(find_weight('M',20).T,find_weather('2018-01-01'))

array([-0.2302973])

In [231]:
find_weather('2018-01-01')

array([-4.5, -1.7,  1.8,  2. ,  2.3,  1.3, -0.7,  2.7, -1.3,  2.1, -0.3,
        3.3,  1. ,  6.4, -2.8, -0.2])

In [218]:
np.dot(find_weight(buy_2018[['sex']],20).T,find_weather('2018-01-01'))

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [215]:
buy_2018.head()

date sex age sm_pr  quant
0 2018-01-01   F  20   가공란     37
1 2018-01-01   F  30   가공란     16
2 2018-01-01   F  40   가공란      9
3 2018-01-01   F  50   가공란      3
4 2018-01-01   M  20   가공란     13

In [213]:
buy_2018['weather'] = np.dot((buy_2018.apply(find_weightsex(,buy_2018.age),find_weather(buy_2018.date))

SyntaxError: invalid syntax (<ipython-input-213-b5116e0c3d19>, line 1)