In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('C:/pythonworks/miniminiproject/data/temp_result/buy_2018_mean_temp.csv',encoding='euc-kr')

In [17]:
df.mean_temp.unique()

array([-0.29705431, -0.29476613, -0.22679291, ..., -3.12508254,
       -2.98984424, -2.8458605 ])

In [15]:
df.loc[df.date == '2018-01-01'].sort_values('sex',ascending = False)

Unnamed: 0        date sex  age        sm_pr  quant  mean_temp
1614        1614  2018-01-01   M   60          흰우유      4  -0.078885
1320        1320  2018-01-01   M   60         커피음료      5  -0.078885
898          898  2018-01-01   M   30   아몬드유/코코넛밀크     10  -0.282246
525          525  2018-01-01   M   20  딸기/복분자/블루베리      5  -0.230297
526          526  2018-01-01   M   30  딸기/복분자/블루베리      9  -0.282246
527          527  2018-01-01   M   40  딸기/복분자/블루베리      7  -0.224065
897          897  2018-01-01   M   20   아몬드유/코코넛밀크      1  -0.230297
1129        1129  2018-01-01   M   20     인삼/수삼/산삼      2  -0.230297
1130        1130  2018-01-01   M   30     인삼/수삼/산삼      8  -0.282246
1328        1328  2018-01-01   M   50      코코아/핫초코      5  -0.150963
532          532  2018-01-01   M   20         딸기우유      5  -0.230297
533          533  2018-01-01   M   30         딸기우유      5  -0.282246
534          534  2018-01-01   M   40         딸기우유      2  -0.224065
535          535  2018-01-01   M   50         딸기우유      2  -0.150963
1327        1327  2018-01-01   M   40      코코아/핫초코     12  -0.224065
1326        1326  2018-01-01   M   30      코코아/핫초코     10  -0.282246
1325        1325  2018-01-01   M   20      코코아/핫초코     18  -0.230297
1131        1131  2018-01-01   M   40     인삼/수삼/산삼      5  -0.224065
540          540  2018-01-01   M   20          랍스타      1  -0.230297
541          541  2018-01-01   M   30          랍스타      2  -0.282246
542          542  2018-01-01   M   40          랍스타      1  -0.224065
1132        1132  2018-01-01   M   50     인삼/수삼/산삼      1  -0.150963
1133        1133  2018-01-01   M   60     인삼/수삼/산삼      1  -0.078885
899          899  2018-01-01   M   40   아몬드유/코코넛밀크      2  -0.224065
1334        1334  2018-01-01   M   20  콜라겐/코큐텐 영양제      1  -0.230297
1335        1335  2018-01-01   M   30  콜라겐/코큐텐 영양제     13  -0.282246
508          508  2018-01-01   M   30           두유     85  -0.282246
1347        1347  2018-01-01   M   60       콩나물/숙주      1  -0.078885
1346        1346  2018-01-01   M   50       콩나물/숙주      1  -0.150963
498          498  2018-01-01   M   20        돼지 곱창     74  -0.230297
...          ...         ...  ..  ...          ...    ...        ...
686          686  2018-01-01   F   30         배추김치     28  -0.294766
685          685  2018-01-01   F   20         배추김치      8  -0.297054
679          679  2018-01-01   F   60     배/포도/과일즙      3  -0.074511
678          678  2018-01-01   F   50     배/포도/과일즙     16  -0.148914
676          676  2018-01-01   F   30     배/포도/과일즙     52  -0.294766
717          717  2018-01-01   F   50           부추      1  -0.148914
675          675  2018-01-01   F   20     배/포도/과일즙     24  -0.297054
669          669  2018-01-01   F   50          반찬류      8  -0.148914
668          668  2018-01-01   F   40          반찬류     16  -0.226793
667          667  2018-01-01   F   30          반찬류     20  -0.294766
666          666  2018-01-01   F   20          반찬류     20  -0.297054
661          661  2018-01-01   F   50       반건조고구마     16  -0.148914
689          689  2018-01-01   F   60         배추김치      3  -0.074511
695          695  2018-01-01   F   30          백김치      3  -0.294766
696          696  2018-01-01   F   40          백김치      2  -0.226793
697          697  2018-01-01   F   50          백김치      2  -0.148914
699          699  2018-01-01   F   20          보리차      1  -0.297054
700          700  2018-01-01   F   30          보리차     11  -0.294766
701          701  2018-01-01   F   40          보리차      9  -0.226793
702          702  2018-01-01   F   50          보리차      1  -0.148914
703          703  2018-01-01   F   60          보리차      3  -0.074511
705          705  2018-01-01   F   20   복분자/석류/과실즙     17  -0.297054
706          706  2018-01-01   F   30   복분자/석류/과실즙     39  -0.294766
707          707  2018-01-01   F   40   복분자/석류/과실즙     30  -0.226793
708          708  2018-01-01   F   50   복분자/석류/과실즙     17  -0.148914
709          709  2018-01-01   F   60   복분자/석류/과실즙      7  -0.074511
714 

In [9]:
a.shape

(3, 2, 4)

In [19]:
a = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])

In [20]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [21]:
b = np.array([[[1,2],[3,4],[2,3],[4,5]],[[1,2],[3,4],[2,3],[4,5]],[[1,2],[3,4],[2,3],[4,5]]])

In [25]:
b

array([[[1, 2],
        [3, 4],
        [2, 3],
        [4, 5]],

       [[1, 2],
        [3, 4],
        [2, 3],
        [4, 5]],

       [[1, 2],
        [3, 4],
        [2, 3],
        [4, 5]]])

In [23]:
b.shape

(3, 4, 2)

In [16]:
b = b.reshape(3,4,2)

In [26]:
1+6+6+16

29

In [24]:
np.matmul(a,b)

array([[[ 29,  39],
        [ 69,  95]],

       [[109, 151],
        [149, 207]],

       [[189, 263],
        [229, 319]]])

In [14]:
a = np.arange(24).reshape(2,3,4)
a
#array([[[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]],
#
#       [[12, 13, 14, 15],
#        [16, 17, 18, 19],
#        [20, 21, 22, 23]]])

b = np.arange(24).reshape(2,4,3)
b
#array([[[ 0,  1,  2],
#        [ 3,  4,  5],
#        [ 6,  7,  8],
#        [ 9, 10, 11]],
#
#       [[12, 13, 14],
#        [15, 16, 17],
#        [18, 19, 20],
#        [21, 22, 23]]])

np.matmul(a,b)
#array([[[  42,   48,   54],
#        [ 114,  136,  158],
#        [ 186,  224,  262]],
#
#       [[ 906,  960, 1014],
#        [1170, 1240, 1310],
#        [1434, 1520, 1606]]])

np.matmul(a,b).shape
# (2, 3, 3)

(2, 3, 3)

In [13]:
np.matmul(b,a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

array([[[1, 2],
        [3, 4],
        [2, 3],
        [4, 5]],

       [[1, 2],
        [3, 4],
        [2, 3],
        [4, 5]],

       [[1, 2],
        [3, 4],
        [2, 3],
        [4, 5]]])